import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import Navigation from "~/components/shared/Navigation";
import { ScrollToTop } from "~/components/shared/ScrollToTop";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider>
					<Navigation />
					<div className="min-h-screen bg-gradient-to-br from-slate-50 via-emerald-50 to-blue-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800">
						{children}
						<ScrollToTop />
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
