import "~/styles/globals.css";

import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";
import Navigation from "~/components/shared/Navigation";
import { ScrollToTop } from "~/components/shared/ScrollToTop";
import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/shared/providers/ThemeProvider";

export const metadata: Metadata = {
	title: "Dev Notes",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const ubuntu = Ubuntu_Mono({
	weight: "400"
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${ubuntu}`}>
			<body>
				<TRPCReactProvider>
					<ThemeProvider>
						<Navigation />
						<div className="min-h-screen bg-gradient-to-br from-slate-50 via-emerald-50 to-blue-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-800">
							{children}
							<ScrollToTop />
						</div>
					</ThemeProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
